### ISSUE TITLE
Trackmania.io shows author medal for all secret times

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/tmio#128]
The author set the secret threshold to be the gold time. I only have gold on this map, but the site shows I have author
https://trackmania.io/#/leaderboard/6pfI5syI4WRZomNz3L9XdHstXSg

![Image](https://github.com/user-attachments/assets/88b9e846-1e76-4dd8-8e1b-981c9db36108)

**Comment by davidbmaier** [comment]
Fixed, secret times shouldn't show any medals anymore.

**Comment by ezio416** [comment]
sorry but this isn't totally fixed, the big medal still shows

![Image](https://github.com/user-attachments/assets/e7760917-3cb6-47ac-b254-24a528b25479)

**Comment by davidbmaier** [comment]
Ah right, forgot about the PB - thanks, will take another look later this week 👍

**Comment by davidbmaier** [comment]
PB medals should be fixed as well now.
